name: celsflair
favicon: null
layout_spectrum: 0.18025047914125025
typography_spectrum: 0.7267239869106561
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b9a504'
    - '#d0d3be'
    - '#242618'
    - '#7d6b05'
  brandStrength: 0.7226113013457507
  lightness: 0.8667711215093732
  saturation: 0.8861704042647034
  rhythmicContrast: 0.8733389850240201
purpose: []
