typography_spectrum: 0.726723
color:
  brandColors:
    - '#FFFFFF'
    - '#B9A504'
    - '#D0D3BE'
    - '#242618'
    - '#7D6B05'
  brandStrength: 0.722611
  lightness: 0.866771
  saturation: 0.88617
  rhythmicContrast: 0.873338
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.256809
analytics:
  google: null
  facebook: null
  twitter: null
name: celflair
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About me
    id: 62fb78db-80ae-42db-af7b-2bc35826674d
    type: content
favicon: null
title: Personal blog
purpose: []
