analytics: {}
color:
  brandColors:
    - '#FFFFFF'
    - '#B9A504'
    - '#D0D3BE'
    - '#242618'
    - '#7D6B05'
  brandStrength: 0.722611
  lightness: 0.866771
  rhythmicContrast: 0.873338
  saturation: 0.88617
cta: {}
layout_spectrum: 0.256809
name: celsflair
opengraph: {}
purpose: []
typography_spectrum: 0.726723
