name: celflair
favicon: null
layout_spectrum: 0.256809
typography_spectrum: 0.726723
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#B9A504'
    - '#D0D3BE'
    - '#242618'
    - '#7D6B05'
  brandStrength: 0.722611
  lightness: 0.866771
  saturation: 0.88617
  rhythmicContrast: 0.873338
purpose: []
